local map = require("core.utils").map

map("n", "j", "h")
map("n", "k", "j")
map("n", "l", "k")
map("n", "ö", "l")
map("n", "h", "%")
map("n", "ß", "$")
map("n", "Y", "y$")
map("n", "ä", "za")
map("n", "<C-k>", "<Esc>:m .+1<CR>==gn")
map("n", "<C-l>", "<Esc>:m .-2<CR>==gn")
map("n", "<leader>t", ":TodoTelescope<CR>")
map("n", "s", ":w<CR>")
map("v", "j", "h")
map("v", "k", "j")
map("v", "l", "k")
map("v", "ö", "l")
map("v", "h", "%")
map("v", "ß", "$")
map("v", "Y", "y$")
map("v", "<leader>a", ":LiveEasyAlign<CR>")
map("v", "<C-k>", ":m '>+1<CR>gv=gv")
map("v", "<C-l>", ":m '<-2<CR>gv=gv")
map("i", "<C-k>", "<Esc>:m .+1<CR>==gi")
map("i", "<C-l>", "<Esc>:m .-2<CR>==gi")

vim.cmd("set foldcolumn=1")
vim.cmd("set foldenable")
vim.cmd("set foldlevel=0")
vim.cmd("set foldmethod=indent")
vim.cmd("set foldnestmax=1")

